name: Tests

on: [push, pull_request]

env:
  FORCE_COLOR: 2

permissions:
  contents: read

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # FIXME: Remove 14/14/16 once repo setting is updated
        node: [12, 14, 16, 18, 20, 24, 26]

    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
        if: ${{ matrix.node >= 18 }}

      - run: npm test
        if: ${{ matrix.node >= 18 }}
